### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by l3ender** [bojand/gcall#2]
I'm getting an error trying to use `gcall`. I cloned the repo and am trying to run one of the provided test protos and am getting the following error:

```
-> gcall -p ./test/protos/route_guide.proto
/Users/ross/.nvm/versions/node/v12.13.1/lib/node_modules/gcall/gcall.js:98
  gservice.methods.forEach(md => console.log(getCallDescription(md)))
                   ^

TypeError: Cannot read property 'forEach' of undefined
    at Object.<anonymous> (/Users/ross/.nvm/versions/node/v12.13.1/lib/node_modules/gcall/gcall.js:98:20)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
```

NPM details (through [NVM](https://github.com/nvm-sh/nvm)):
```
-> nvm --version
0.35.1

-> npm --version
6.12.1
```

Running on Mac OSX Catalina 10.15.3.

**Comment by 70747H** [comment]
@l3ender 
I had the same issue and it worked with me after providing the host and the function to be called
ex:
`gcall -p ~/dev/playground/nest-grpc/src/service/hello.proto -h localhost:5000 findOne`
